trigger:
- main

pool:
  name: agent-vayu

variables:
- group: docker-credentials

- name: dockerHubRepo
  value: pavankumarch1219/dotnet-application

- name: imageTag
  value: $(Build.BuildId)

stages:

# ---------------- BUILD STAGE ----------------

- stage: Build
  displayName: Build .NET Application
  jobs:
  - job: BuildDotnet
    steps:

    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.x'

    - script: |
        echo "Restoring dependencies"
        dotnet restore

        echo "Building project"
        dotnet build --configuration Release
      displayName: Restore & Build Project


# ---------------- DOCKER BUILD STAGE ----------------

- stage: DockerBuild
  displayName: Build and Push Docker Image
  dependsOn: Build
  jobs:
  - job: DockerBuild
    steps:

    - script: |
        echo "Building Docker Image"
        docker build -t $(dockerHubRepo):$(imageTag) .
      displayName: Build Docker Image

    - script: |
        echo "Logging into DockerHub"
        docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)

        echo "Pushing Docker Image"
        docker push $(dockerHubRepo):$(imageTag)
      displayName: Push Docker Image


# ---------------- DEPLOY TO KUBERNETES ----------------

- stage: Deploy
  displayName: Deploy to Kubernetes
  dependsOn: DockerBuild
  jobs:
  - job: DeployToK8s
    steps:

    - script: |
        echo "Updating Kubernetes Deployment"

        kubectl set image deployment/dotnet-app \
        dotnet-app=$(dockerHubRepo):$(imageTag)

        echo "Deployment updated successfully"
      displayName: Deploy to Kubernetes
```
