trigger:
- main

pool:
  name: agent-vayu

variables:
- group: docker-credentials

- name: dockerHubRepo
  value: pavankumarch1219

- name: imageTag
  value: $(Build.BuildId)

stages:

# ---------------- BUILD ----------------
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: sdk
        version: 10.0.x

    - script: |
        dotnet restore src/WebApp/WebApp.csproj
        dotnet build src/WebApp/WebApp.csproj --configuration Release --no-restore
      displayName: Build Project


# ---------------- DOCKER BUILD ----------------
- stage: DockerBuild
  dependsOn: Build
  jobs:
  - job: DockerJob
    steps:
    - script: |
        echo "Login to DockerHub"
        echo "$(DOCKER_PASSWORD)" | docker login -u "$(DOCKER_USERNAME)" --password-stdin

        echo "Build Catalog API"
        docker build -t $(dockerHubRepo)/catalog-api:$(imageTag) -f src/Catalog.API/Dockerfile src/Catalog.API
        docker push $(dockerHubRepo)/catalog-api:$(imageTag)

        echo "Build Basket API"
        docker build -t $(dockerHubRepo)/basket-api:$(imageTag) -f src/Basket.API/Dockerfile src/Basket.API
        docker push $(dockerHubRepo)/basket-api:$(imageTag)

        echo "Build Identity API"
        docker build -t $(dockerHubRepo)/identity-api:$(imageTag) -f src/Identity.API/Dockerfile src/Identity.API
        docker push $(dockerHubRepo)/identity-api:$(imageTag)

        echo "Build Ordering API"
        docker build -t $(dockerHubRepo)/ordering-api:$(imageTag) -f src/Ordering.API/Dockerfile src/Ordering.API
        docker push $(dockerHubRepo)/ordering-api:$(imageTag)
      displayName: Build & Push Images


# ---------------- DEPLOY ----------------
- stage: Deploy
  dependsOn: DockerBuild
  jobs:
  - job: DeployJob
    steps:
    - script: |
        kubectl apply -f k8s/

        kubectl set image deployment/catalog-api catalog-api=$(dockerHubRepo)/catalog-api:$(imageTag)
        kubectl set image deployment/basket-api basket-api=$(dockerHubRepo)/basket-api:$(imageTag)
        kubectl set image deployment/identity-api identity-api=$(dockerHubRepo)/identity-api:$(imageTag)
        kubectl set image deployment/ordering-api ordering-api=$(dockerHubRepo)/ordering-api:$(imageTag)

        kubectl rollout status deployment/catalog-api
        kubectl rollout status deployment/basket-api
        kubectl rollout status deployment/identity-api
        kubectl rollout status deployment/ordering-api

        kubectl get pods
        kubectl get svc
      displayName: Deploy to Kubernetes
