apiVersion: apps/v1
kind: Deployment
metadata:
  name: basket-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: basket-api

  template:
    metadata:
      labels:
        app: basket-api

    spec:
      containers:
      - name: basket-api
        image: pavankumarch1219/basket-api:latest

        ports:
        - containerPort: 80

        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"

        - name: ConnectionStrings__basketdb
          value: "Host=postgres;Port=5432;Database=basketdb;Username=postgres;Password=postgres"

        - name: EventBus__HostName
          value: "rabbitmq"

        - name: Redis__ConnectionString
          value: "redis:6379"
