apiVersion: apps/v1
kind: Deployment
metadata:
  name: basket-api
  namespace: eshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: basket-api

  template:
    metadata:
      labels:
        app: basket-api

    spec:
      containers:
      - name: basket-api
        image: pavankumarch1219/basket-api:latest

        ports:
        - containerPort: 80

        envFrom:
        - configMapRef:
            name: app-config

        env:
        - name: ConnectionStrings__basketdb
          value: "Host=postgres;Port=5432;Database=basketdb;Username=postgres;Password=postgres"
