apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
  namespace: eshop
  labels:
    app: catalog-api

spec:
  replicas: 2

  selector:
    matchLabels:
      app: catalog-api

  template:
    metadata:
      labels:
        app: catalog-api

    spec:
      containers:
        - name: catalog-api
          image: pavankumarch1219/catalog-api:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 80

          env:
            # 🔹 Database connection
            - name: ConnectionStrings__catalogdb
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: CATALOG_DB

            # 🔹 RabbitMQ credentials
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_USER

            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_PASS

            # 🔹 ConfigMap values
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBITMQ_HOST

            # 🔹 EventBus connection
            - name: ConnectionStrings__EventBus
              value: "amqp://$(RABBITMQ_USER):$(RABBITMQ_PASS)@$(RABBITMQ_HOST):5672"

            # 🔹 ASP.NET config
            - name: ASPNETCORE_URLS
              value: "http://+:80"

            - name: ASPNETCORE_Kestrel__EndpointDefaults__Protocols
              value: "Http1AndHttp2"

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /health/ready
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 10
