apiVersion: v1
kind: Service
metadata:
  name: dotnet-app
  namespace: eshop
  labels:
    app: dotnet-app
spec:
  type: NodePort
  selector:
    app: dotnet-app
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30007
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app
  namespace: eshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-app
  template:
    metadata:
      labels:
        app: dotnet-app
    spec:
      # =========================
      # WAIT FOR REDIS
      # =========================
      initContainers:
        - name: wait-for-redis
          image: busybox
          command:
            - sh
            - -c
            - |
              echo "Waiting for Redis...";
              until nc -z redis 6379;
              do
                sleep 2;
              done;
              echo "Redis is ready";
      containers:
        - name: dotnet-app
          image: pavankumarch1219/dotnet-application:latest
          ports:
            - containerPort: 80
          env:
            # =========================
            # CORE SETTINGS
            # =========================
            - name: ASPNETCORE_URLS
              value: "http://+:80"
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"

            # =========================
            # INTERNAL SERVICES
            # =========================
            - name: IdentityUrl
              value: "http://identity-api"
            - name: CatalogUrl
              value: "http://catalog-api"
            - name: BasketUrl
              value: "http://basket-api"
            - name: OrderingUrl
              value: "http://ordering-api"

            # =========================
            # REDIS
            # =========================
            - name: ConnectionStrings__Redis
              value: "redis:6379"

            # =========================
            # OIDC CALLBACK
            # =========================
            - name: CallBackUrl
              value: "http://20.220.149.85:30007"

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          # =========================
          # STABLE PROBES
          # =========================
          startupProbe:
            tcpSocket:
              port: 80
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 15
