apiVersion: v1
kind: Service
metadata:
  name: identity-api
  namespace: eshop

spec:
  type: ClusterIP
  selector:
    app: identity-api

  ports:
    - port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-api
  namespace: eshop

spec:
  replicas: 2

  selector:
    matchLabels:
      app: identity-api

  template:
    metadata:
      labels:
        app: identity-api

    spec:
      initContainers:
        - name: wait-for-redis
          image: busybox
          command: ["sh", "-c", "until nc -z redis 6379; do echo waiting for redis; sleep 2; done"]

      containers:
        - name: identity-api
          image: pavankumarch1219/identity-api:latest

          ports:
            - containerPort: 80

          env:
            - name: ConnectionStrings__IdentityDb
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: ConnectionStrings__IdentityDb

            - name: ConnectionStrings__Redis
              value: redis

            - name: ASPNETCORE_URLS
              value: http://+:80

          # FIXED PROBES
          startupProbe:
            tcpSocket:
              port: 80
            failureThreshold: 30

          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10

          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 30
