apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eshop-ingress
  namespace: eshop
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  ingressClassName: nginx

  rules:
  - http:
      paths:

      - path: /
        pathType: Prefix
        backend:
          service:
            name: dotnet-app
            port:
              number: 80

      - path: /catalog
        pathType: Prefix
        backend:
          service:
            name: catalog-service
            port:
              number: 80

      - path: /basket
        pathType: Prefix
        backend:
          service:
            name: basket-api
            port:
              number: 80

      - path: /identity
        pathType: Prefix
        backend:
          service:
            name: identity-service
            port:
              number: 80
