apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: eshop
  labels:
    app: postgres

spec:
  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
        - name: postgres
          image: pgvector/pgvector:pg15

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              value: postgres

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_PASSWORD

          volumeMounts:
            #  FIX: Use PVC (persistent storage)
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage

            #  init script
            - mountPath: /docker-entrypoint-initdb.d
              name: postgres-init

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 20
            periodSeconds: 10

          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 5
            periodSeconds: 5

      volumes:
        #  FIXED: use PVC instead of emptyDir
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc

        - name: postgres-init
          configMap:
            name: postgres-init
