apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: eshop
  labels:
    app: rabbitmq

spec:
  replicas: 1

  selector:
    matchLabels:
      app: rabbitmq

  template:
    metadata:
      labels:
        app: rabbitmq

    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management

          ports:
            - containerPort: 5672
            - containerPort: 15672

          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_USER

            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_PASS

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          livenessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "-q", "ping"]
            initialDelaySeconds: 60
            periodSeconds: 30

          readinessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "-q", "check_port_connectivity"]
            initialDelaySeconds: 30
            periodSeconds: 15

          volumeMounts:
            - name: rabbitmq-storage
              mountPath: /var/lib/rabbitmq

      volumes:
        - name: rabbitmq-storage
          emptyDir: {}
