apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: eshop

type: Opaque

stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: Sahyadri
  CONNECTION_STRING: Host=postgres;Port=5432;Database=catalogdb;Username=postgres;Password=Sahyadri
