apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: eshop
type: Opaque

stringData:
  # =========================
  #  POSTGRES
  # =========================
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: Sahyadri

  # =========================
  #  DATABASE CONNECTIONS
  # =========================
  ConnectionStrings__CatalogDb: Host=postgres;Port=5432;Database=catalogdb;Username=postgres;Password=Sahyadri
  ConnectionStrings__BasketDb: Host=postgres;Port=5432;Database=basketdb;Username=postgres;Password=Sahyadri
  ConnectionStrings__IdentityDb: Host=postgres;Port=5432;Database=identitydb;Username=postgres;Password=Sahyadri
  ConnectionStrings__OrderingDb: Host=postgres;Port=5432;Database=orderingdb;Username=postgres;Password=Sahyadri

  # =========================
  #  REDIS
  # =========================
  ConnectionStrings__Redis: redis

  # =========================
  #  RABBITMQ (MERGED)
  # =========================
  RABBITMQ_USER: guest
  RABBITMQ_PASS: guest
  ConnectionStrings__EventBus: amqp://guest:guest@rabbitmq:5672
